MAKEFLAGS += --silent

make:
#	g++ -std=c++17 block.cpp -o block -lssl -lcrypto
	g++ -std=c++17 blockchain.cpp -o blockchain.exe -lssl -lcrypto && ./blockchain.exe && printf "\n\n --- Program compiled and run succesfully\n"
run:
	./blockchain.exe
